import type { CityMarket, Listing } from "@/lib/types";
import { roommateMedia } from "@/lib/roommates/media";

export const featuredListings: Listing[] = [
  {
    id: "harare-avondale-cottage",
    title: "Verified garden cottage near Avondale shops",
    city: "Harare",
    suburb: "Avondale",
    price: 420,
    currency: "USD",
    intent: "rent",
    type: "cottage",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.cottage,
    verified: true,
    availableFrom: "Available now",
    amenities: ["Solar backup", "Borehole", "Wi-Fi", "Parking"],
    description:
      "A quiet one-bedroom garden cottage with reliable water, solar backup, secure parking, and fast access to Avondale shops.",
    landlordName: "Tariro Moyo",
    landlordVerified: true,
    phone: "+263 77 123 4567",
    whatsapp: "+263771234567",
    distanceToCbdKm: 4.2,
    nearby: ["Avondale shops", "Belvedere Medical Centre", "Harare CBD"],
    views: 842,
    saves: 64,
    enquiries: 28,
    trustScore: 96,
    highlight: "Best for quiet professionals",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single", "couple"],
      acceptedMaritalStatuses: ["single", "married", "partnered", "divorced", "widowed"],
      maxOccupants: 2,
      genderPreference: "any",
      minAge: 21,
      maxAge: 45,
    },
  },
  {
    id: "bulawayo-hillside-house",
    title: "Family home with borehole in Hillside",
    city: "Bulawayo",
    suburb: "Hillside",
    price: 950,
    currency: "USD",
    intent: "rent",
    type: "house",
    bedrooms: 4,
    bathrooms: 2,
    image: "/images/bulawayo-family-house.png",
    verified: true,
    availableFrom: "1 July 2026",
    amenities: ["Borehole", "Security wall", "Garden", "Pets allowed"],
    description:
      "A spacious family home with a private garden, borehole, perimeter security, and room for remote work or study.",
    landlordName: "Ndlovu Property Group",
    landlordVerified: true,
    phone: "+263 78 555 2101",
    whatsapp: "+263785552101",
    distanceToCbdKm: 6.8,
    nearby: ["Hillside shops", "Mater Dei Hospital", "Hillside Teachers College"],
    views: 621,
    saves: 48,
    enquiries: 19,
    trustScore: 98,
    highlight: "Family-ready with private garden",
    tenantPreferences: {
      acceptedHouseholdTypes: ["couple", "small_family", "large_family"],
      acceptedMaritalStatuses: ["married", "partnered", "single", "divorced", "widowed"],
      maxOccupants: 6,
      genderPreference: "any",
      minAge: 25,
      maxAge: 60,
    },
  },
  {
    id: "gweru-senga-room",
    title: "Student-friendly room close to MSU transport",
    city: "Gweru",
    suburb: "Senga",
    price: 110,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room,
    verified: false,
    availableFrom: "Available now",
    amenities: ["Wi-Fi", "Water tank", "Shared kitchen", "Transport nearby"],
    description:
      "A clean room suited to students and young professionals, close to transport routes and shared amenities.",
    landlordName: "Memory Chikanda",
    landlordVerified: false,
    phone: "+263 71 900 2214",
    whatsapp: "+263719002214",
    distanceToCbdKm: 3.1,
    nearby: ["MSU transport", "Senga shops", "Gweru CBD"],
    views: 390,
    saves: 31,
    enquiries: 16,
    trustScore: 82,
    highlight: "Student-friendly near transport",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 18,
      maxAge: 30,
    },
  },
  {
    id: "kwekwe-cbd-flat",
    title: "Compact flat within walking distance of Kwekwe CBD",
    city: "Kwekwe",
    suburb: "Newtown",
    price: 260,
    currency: "USD",
    intent: "rent",
    type: "flat",
    bedrooms: 2,
    bathrooms: 1,
    image: roommateMedia.flat,
    verified: true,
    availableFrom: "15 July 2026",
    amenities: ["Water tank", "Parking", "Security", "Prepaid ZESA"],
    description:
      "A practical two-bedroom flat for tenants who need quick CBD access, reliable water storage, and controlled parking.",
    landlordName: "C. Nyathi",
    landlordVerified: true,
    phone: "+263 77 440 1209",
    whatsapp: "+263774401209",
    distanceToCbdKm: 1.4,
    nearby: ["Kwekwe CBD", "General Hospital", "OK Kwekwe"],
    views: 514,
    saves: 42,
    enquiries: 22,
    trustScore: 91,
    highlight: "Walkable CBD access",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single", "couple", "small_family"],
      acceptedMaritalStatuses: ["single", "married", "partnered", "divorced", "widowed"],
      maxOccupants: 4,
      genderPreference: "any",
      minAge: 21,
      maxAge: 55,
    },
  },
  {
    id: "harare-belvedere-room",
    title: "Furnished room in Belvedere — Wi-Fi included",
    city: "Harare",
    suburb: "Belvedere",
    price: 195,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room2,
    verified: true,
    availableFrom: "Available now",
    amenities: ["Furnished", "Wi-Fi", "Water tank", "Shared kitchen"],
    description: "Bright furnished room in a quiet Belvedere home, ideal for nurses and young professionals on shift work.",
    landlordName: "Patience Dube",
    landlordVerified: true,
    phone: "+263 77 210 8891",
    whatsapp: "+263772108891",
    distanceToCbdKm: 3.8,
    nearby: ["Belvedere Medical Centre", "Belvedere shops", "Harare CBD"],
    views: 467,
    saves: 38,
    enquiries: 21,
    trustScore: 89,
    highlight: "Furnished with Wi-Fi",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single", "divorced", "widowed"],
      maxOccupants: 1,
      genderPreference: "female",
      minAge: 20,
      maxAge: 40,
    },
  },
  {
    id: "harare-borrowdale-flat-share",
    title: "Shared flat in Borrowdale — 2 rooms available",
    city: "Harare",
    suburb: "Borrowdale",
    price: 380,
    currency: "USD",
    intent: "rent",
    type: "flat",
    bedrooms: 2,
    bathrooms: 2,
    image: roommateMedia.flat2,
    verified: true,
    availableFrom: "1 Aug 2026",
    amenities: ["Furnished", "Parking", "Security", "Wi-Fi", "Solar backup"],
    description: "Modern flat share in a secure Borrowdale complex — two private rooms with shared living space.",
    landlordName: "Borrowdale Estates",
    landlordVerified: true,
    phone: "+263 77 330 4412",
    whatsapp: "+263773304412",
    distanceToCbdKm: 8.2,
    nearby: ["Sam Levy Village", "Borrowdale Brooke", "Pomona"],
    views: 612,
    saves: 52,
    enquiries: 27,
    trustScore: 95,
    highlight: "Premium flat share",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single", "couple"],
      acceptedMaritalStatuses: ["single", "married", "partnered"],
      maxOccupants: 2,
      genderPreference: "any",
      minAge: 23,
      maxAge: 45,
    },
  },
  {
    id: "harare-mount-pleasant-room",
    title: "Quiet room near Mount Pleasant shops",
    city: "Harare",
    suburb: "Mount Pleasant",
    price: 250,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room3,
    verified: true,
    availableFrom: "15 Aug 2026",
    amenities: ["Wi-Fi", "Parking", "Borehole", "Shared kitchen"],
    description: "Spacious room in a family home near UZ and Mount Pleasant shops — quiet household preferred.",
    landlordName: "Mrs. Chigwada",
    landlordVerified: true,
    phone: "+263 77 551 2200",
    whatsapp: "+263775512200",
    distanceToCbdKm: 5.1,
    nearby: ["Mount Pleasant shops", "University of Zimbabwe", "Avondale"],
    views: 388,
    saves: 29,
    enquiries: 15,
    trustScore: 87,
    highlight: "Near UZ campus",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 19,
      maxAge: 35,
    },
  },
  {
    id: "bulawayo-cbd-room",
    title: "Affordable CBD room — walking distance to work",
    city: "Bulawayo",
    suburb: "CBD",
    price: 140,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room4,
    verified: false,
    availableFrom: "Available now",
    amenities: ["Wi-Fi", "Water tank", "Shared kitchen"],
    description: "Budget-friendly room in Bulawayo CBD for workers and students who need central access.",
    landlordName: "Sipho Ndlovu",
    landlordVerified: false,
    phone: "+263 78 220 1100",
    whatsapp: "+263782201100",
    distanceToCbdKm: 0.5,
    nearby: ["Bulawayo CBD", "City Hall", "Ascot"],
    views: 291,
    saves: 22,
    enquiries: 11,
    trustScore: 78,
    highlight: "CBD on a budget",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "male",
      minAge: 18,
      maxAge: 35,
    },
  },
  {
    id: "bulawayo-kumalo-cottage",
    title: "Garden cottage in Kumalo — private entrance",
    city: "Bulawayo",
    suburb: "Kumalo",
    price: 350,
    currency: "USD",
    intent: "rent",
    type: "cottage",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.cottage2,
    verified: true,
    availableFrom: "1 Sep 2026",
    amenities: ["Solar backup", "Borehole", "Parking", "Wi-Fi", "Garden"],
    description: "Self-contained garden cottage with private entrance in upscale Kumalo — ideal for professionals.",
    landlordName: "Kumalo Properties",
    landlordVerified: true,
    phone: "+263 78 440 3300",
    whatsapp: "+263784403300",
    distanceToCbdKm: 4.5,
    nearby: ["Kumalo shops", "Hillside", "Bulawayo CBD"],
    views: 445,
    saves: 35,
    enquiries: 18,
    trustScore: 93,
    highlight: "Private garden cottage",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single", "couple"],
      acceptedMaritalStatuses: ["single", "married", "partnered"],
      maxOccupants: 2,
      genderPreference: "any",
      minAge: 25,
      maxAge: 50,
    },
  },
  {
    id: "gweru-ridgemont-room",
    title: "Room in Ridgemont — close to Gweru CBD",
    city: "Gweru",
    suburb: "Ridgemont",
    price: 130,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.shared,
    verified: true,
    availableFrom: "Available now",
    amenities: ["Wi-Fi", "Shared kitchen", "Water tank", "Transport nearby"],
    description: "Clean room in Ridgemont with shared kitchen — popular with MSU students and interns.",
    landlordName: "Memory Chikanda",
    landlordVerified: true,
    phone: "+263 71 900 2214",
    whatsapp: "+263719002214",
    distanceToCbdKm: 2.4,
    nearby: ["Gweru CBD", "Ridgemont shops", "MSU transport"],
    views: 334,
    saves: 26,
    enquiries: 14,
    trustScore: 84,
    highlight: "Student-friendly Ridgemont",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 18,
      maxAge: 28,
    },
  },
  {
    id: "mutare-chikanga-room",
    title: "Budget room in Chikanga — shared amenities",
    city: "Mutare",
    suburb: "Chikanga",
    price: 120,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room5,
    verified: false,
    availableFrom: "Available now",
    amenities: ["Shared kitchen", "Water tank", "Transport nearby"],
    description: "Affordable room in Chikanga for interns and young workers starting out in Mutare.",
    landlordName: "Tendai Mukwena",
    landlordVerified: false,
    phone: "+263 77 880 9900",
    whatsapp: "+263778809900",
    distanceToCbdKm: 4.2,
    nearby: ["Chikanga shops", "Mutare CBD", "Dangamvura"],
    views: 256,
    saves: 19,
    enquiries: 9,
    trustScore: 76,
    highlight: "Budget Mutare room",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 18,
      maxAge: 30,
    },
  },
  {
    id: "kwekwe-msasa-room",
    title: "Student room near Kwekwe industrial sites",
    city: "Kwekwe",
    suburb: "Msasa Park",
    price: 100,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room6,
    verified: true,
    availableFrom: "Available now",
    amenities: ["Wi-Fi", "Shared kitchen", "Water tank"],
    description: "Low-cost room in Msasa Park — popular with apprentices and industrial workers.",
    landlordName: "C. Nyathi",
    landlordVerified: true,
    phone: "+263 77 440 1209",
    whatsapp: "+263774401209",
    distanceToCbdKm: 2.8,
    nearby: ["Kwekwe CBD", "Msasa industrial", "OK Kwekwe"],
    views: 312,
    saves: 24,
    enquiries: 13,
    trustScore: 81,
    highlight: "Under US$100/month",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 18,
      maxAge: 32,
    },
  },
  {
    id: "chitungwiza-seke-room",
    title: "Room in Seke — Harare commuter belt",
    city: "Chitungwiza",
    suburb: "Seke Unit A",
    price: 90,
    currency: "USD",
    intent: "rent",
    type: "room",
    bedrooms: 1,
    bathrooms: 1,
    image: roommateMedia.room7,
    verified: false,
    availableFrom: "Available now",
    amenities: ["Shared kitchen", "Water tank", "Transport nearby"],
    description: "Very affordable room in Seke with kombi links to Harare CBD — ideal for budget seekers.",
    landlordName: "Mrs. Moyo",
    landlordVerified: false,
    phone: "+263 77 112 3344",
    whatsapp: "+263771123344",
    distanceToCbdKm: 18.5,
    nearby: ["Seke shops", "Chitungwiza Town Centre", "Harare CBD transport"],
    views: 478,
    saves: 41,
    enquiries: 20,
    trustScore: 74,
    highlight: "Lowest price on HomeLink",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 18,
      maxAge: 40,
    },
  },
  {
    id: "harare-avondale-flat-share",
    title: "House share flat — Avondale West",
    city: "Harare",
    suburb: "Avondale West",
    price: 320,
    currency: "USD",
    intent: "rent",
    type: "flat",
    bedrooms: 3,
    bathrooms: 2,
    image: roommateMedia.flat3,
    verified: true,
    availableFrom: "20 Jul 2026",
    amenities: ["Furnished", "Wi-Fi", "Parking", "Security", "Borehole"],
    description: "Three-bedroom flat share in Avondale West — one room available for a compatible housemate.",
    landlordName: "Tariro Moyo",
    landlordVerified: true,
    phone: "+263 77 123 4567",
    whatsapp: "+263771234567",
    distanceToCbdKm: 4.0,
    nearby: ["Avondale shops", "Belvedere", "Harare CBD"],
    views: 534,
    saves: 44,
    enquiries: 24,
    trustScore: 92,
    highlight: "House share in Avondale",
    tenantPreferences: {
      acceptedHouseholdTypes: ["single"],
      acceptedMaritalStatuses: ["single", "partnered"],
      maxOccupants: 1,
      genderPreference: "any",
      minAge: 22,
      maxAge: 38,
    },
  },
  {
    id: "mutare-murambi-land",
    title: "Residential stand with mountain views",
    city: "Mutare",
    suburb: "Murambi",
    price: 18500,
    currency: "USD",
    intent: "buy",
    type: "land",
    bedrooms: 0,
    bathrooms: 0,
    image: roommateMedia.land,
    verified: true,
    availableFrom: "Ready for transfer",
    amenities: ["Title deeds", "Road access", "Water nearby", "Electricity nearby"],
    description:
      "A residential stand in a growing pocket of Murambi with documented ownership and nearby utility access.",
    landlordName: "Eastern Highlands Realty",
    landlordVerified: true,
    phone: "+263 77 888 3410",
    whatsapp: "+263778883410",
    distanceToCbdKm: 5.5,
    nearby: ["Murambi shops", "Mutare CBD", "Christmas Pass"],
    views: 713,
    saves: 57,
    enquiries: 14,
    trustScore: 94,
    highlight: "Documented stand with utilities nearby",
  },
  {
    id: "harare-cbd-office-suite",
    title: "Ground-floor office suite in Harare CBD",
    city: "Harare",
    suburb: "CBD",
    price: 1200,
    currency: "USD",
    intent: "rent",
    type: "commercial",
    bedrooms: 0,
    bathrooms: 2,
    image: roommateMedia.office,
    verified: true,
    availableFrom: "Available now",
    amenities: ["Parking", "Security", "Generator backup", "Fiber internet"],
    description:
      "A professional ground-floor commercial suite with reception area, open-plan workspace, kitchenette, and dedicated parking in the heart of Harare CBD.",
    landlordName: "Harare Prime Estates",
    landlordVerified: true,
    phone: "+263242123456",
    whatsapp: "+263242123456",
    distanceToCbdKm: 0.3,
    nearby: ["Harare CBD", "Joina City", "Eastgate Centre"],
    views: 562,
    saves: 41,
    enquiries: 23,
    trustScore: 93,
    highlight: "CBD office with parking and fiber",
  },
  {
    id: "victoria-falls-riverside-lodge",
    title: "Riverside holiday lodge near Victoria Falls",
    city: "Victoria Falls",
    suburb: "Chinotimba",
    price: 185,
    currency: "USD",
    intent: "rent",
    type: "holiday_home",
    bedrooms: 3,
    bathrooms: 2,
    image: roommateMedia.lodge,
    verified: true,
    availableFrom: "Available now",
    amenities: ["Wi-Fi", "Parking", "Borehole", "Security", "Garden"],
    description:
      "A premium holiday lodge with Zambezi views, private garden, pool access, and concierge support for Victoria Falls adventures.",
    landlordName: "Tariro Moyo",
    landlordVerified: true,
    phone: "+263 77 123 4567",
    whatsapp: "+263771234567",
    distanceToCbdKm: 2.1,
    nearby: ["Victoria Falls Rainforest", "Lookout Cafe", "Town centre"],
    views: 428,
    saves: 36,
    enquiries: 17,
    trustScore: 97,
    highlight: "Perfect for weekend getaways and family holidays",
    holidayHome: {
      nightlyRate: 185,
      weeklyRate: 1150,
      monthlyRate: 4200,
      minimumStay: 2,
      maximumGuests: 6,
      checkInTime: "14:00",
      checkOutTime: "10:00",
      cleaningFee: 45,
      securityDeposit: 150,
      destination: "Victoria Falls",
      wifiAvailable: true,
      swimmingPool: true,
      airConditioning: true,
      kitchen: true,
      braaiArea: true,
      parking: true,
      petFriendly: false,
      wheelchairAccessible: false,
      houseRules: "No smoking indoors. Quiet hours after 22:00. Maximum 6 guests.",
      nearbyAttractions: "Victoria Falls, Zambezi sunset cruise, helicopter flights, curio markets",
    },
  },
];

export const latestListings = [...featuredListings].sort((a, b) =>
  a.city.localeCompare(b.city),
);

export const cityMarkets: CityMarket[] = [
  {
    name: "Harare",
    listingCount: 1248,
    averageRent: "$380",
    highlights: ["Avondale", "Borrowdale", "CBD", "Mabelreign"],
  },
  {
    name: "Bulawayo",
    listingCount: 684,
    averageRent: "$300",
    highlights: ["Hillside", "Burnside", "CBD", "Pumula"],
  },
  {
    name: "Gweru",
    listingCount: 318,
    averageRent: "$210",
    highlights: ["Senga", "Windsor Park", "CBD", "Mkoba"],
  },
  {
    name: "Mutare",
    listingCount: 246,
    averageRent: "$240",
    highlights: ["Murambi", "Dangamvura", "CBD", "Chikanga"],
  },
];

export const propertyCategories = [
  "Rooms",
  "Houses",
  "Flats",
  "Cottages",
  "Commercial",
  "Land",
  "Holiday Homes",
  "Roommates",
];

export const trustSignals = [
  "Verified landlord identities",
  "Freshness checks for old listings",
  "Duplicate listing detection",
  "WhatsApp-ready enquiries",
  "Saved searches and price alerts",
  "Neighbourhood reviews",
];
