import type { AgentPermissions, AgentSystemSettings, AgentTrainingModule, CommissionRule } from "@/lib/agents/types";

export const DEFAULT_COMMISSION_RULES: CommissionRule[] = [
  {
    id: "rule_sale",
    type: "SALE",
    label: "Agent-sourced sale",
    leadSource: "AGENT",
    scope: "DEFAULT",
    priority: 10,
    reason: "The agent sourced the client while HomeLink provides the brand, CRM, platform, administration, and transaction support.",
    ratePercent: 5,
    homelinkSplitPercent: 40,
    agentSplitPercent: 60,
    minAmount: 0,
    maxAmount: 50000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_sale_homelink",
    type: "SALE",
    label: "HomeLink-sourced sale",
    leadSource: "HOMELINK",
    scope: "DEFAULT",
    priority: 10,
    reason: "HomeLink generated the lead through marketing, technology, brand building, support, and customer acquisition.",
    ratePercent: 5,
    homelinkSplitPercent: 60,
    agentSplitPercent: 40,
    minAmount: 0,
    maxAmount: 50000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_rental",
    type: "RENTAL",
    label: "Agent-sourced rental",
    leadSource: "AGENT",
    scope: "DEFAULT",
    priority: 10,
    reason: "The agent sourced the landlord, tenant, or room owner while HomeLink provides the operating platform and transaction support.",
    ratePercent: 10,
    homelinkSplitPercent: 40,
    agentSplitPercent: 60,
    minAmount: 0,
    maxAmount: 10000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_rental_homelink",
    type: "RENTAL",
    label: "HomeLink-sourced rental",
    leadSource: "HOMELINK",
    scope: "DEFAULT",
    priority: 10,
    reason: "HomeLink generated the enquiry and assigned an agent to inspect, verify, communicate, negotiate, and close.",
    ratePercent: 10,
    homelinkSplitPercent: 60,
    agentSplitPercent: 40,
    minAmount: 0,
    maxAmount: 10000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_management",
    type: "MANAGEMENT",
    label: "Agent-sourced management",
    leadSource: "AGENT",
    scope: "DEFAULT",
    priority: 10,
    reason: "The agent sourced the property management client; HomeLink provides the systems, brand, administration, and support.",
    ratePercent: 8,
    homelinkSplitPercent: 40,
    agentSplitPercent: 60,
    minAmount: 0,
    maxAmount: 8000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_management_homelink",
    type: "MANAGEMENT",
    label: "HomeLink-sourced management",
    leadSource: "HOMELINK",
    scope: "DEFAULT",
    priority: 10,
    reason: "HomeLink generated the management opportunity and supports the agent through operations, systems, and administration.",
    ratePercent: 8,
    homelinkSplitPercent: 60,
    agentSplitPercent: 40,
    minAmount: 0,
    maxAmount: 8000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_referral",
    type: "REFERRAL",
    label: "Referral Commission",
    leadSource: "ANY",
    scope: "DEFAULT",
    priority: 5,
    reason: "Referral commissions are shared according to the active referral rule configured by HomeLink.",
    ratePercent: 3,
    homelinkSplitPercent: 50,
    agentSplitPercent: 50,
    minAmount: 0,
    maxAmount: 5000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_bonus",
    type: "BONUS",
    label: "Performance Bonus",
    leadSource: "ANY",
    scope: "DEFAULT",
    priority: 5,
    reason: "Performance bonuses are set by the active HomeLink bonus rule.",
    ratePercent: 2,
    homelinkSplitPercent: 0,
    agentSplitPercent: 100,
    minAmount: 0,
    maxAmount: 3000,
    vatPercent: 0,
    bonusPercent: 2,
    active: true,
  },
  {
    id: "rule_recurring",
    type: "RECURRING",
    label: "Recurring Management",
    leadSource: "ANY",
    scope: "DEFAULT",
    priority: 5,
    reason: "Recurring management commission follows the active recurring rule configured by HomeLink.",
    ratePercent: 5,
    homelinkSplitPercent: 45,
    agentSplitPercent: 55,
    minAmount: 0,
    maxAmount: 5000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
];

export const DEFAULT_AGENT_PERMISSIONS: AgentPermissions = {
  canListProperties: true,
  canSell: true,
  canRent: true,
  canManageCommercial: true,
  canManageLand: true,
  canViewReports: true,
  canApproveOffers: false,
  canManageClients: true,
  canUploadDocuments: true,
};

export function defaultAgentTrainingModules(): AgentTrainingModule[] {
  return [
    {
      id: "train_intro",
      title: "Welcome to HomeLink Agents",
      description: "Platform overview, brand standards, and compliance basics.",
      type: "VIDEO",
      durationMinutes: 20,
      required: true,
      order: 1,
    },
    {
      id: "train_listings",
      title: "Listing Excellence",
      description: "How to create high-converting listings with photos, video, and availability.",
      type: "DOCUMENT",
      durationMinutes: 30,
      required: true,
      order: 2,
    },
    {
      id: "train_leads",
      title: "Lead Management",
      description: "Accepting leads, scheduling viewings, and closing deals.",
      type: "QUIZ",
      durationMinutes: 25,
      required: true,
      order: 3,
    },
    {
      id: "train_compliance",
      title: "Compliance & Ethics",
      description: "Client data, contracts, and professional conduct.",
      type: "ASSIGNMENT",
      durationMinutes: 15,
      required: true,
      order: 4,
    },
  ];
}

export function createDefaultAgentSettings(): AgentSystemSettings {
  return {
    commissionRules: DEFAULT_COMMISSION_RULES.map((r) => ({ ...r })),
    leadAssignmentStrategy: "TERRITORY",
    approvalWorkflow: {
      mode: "MANUAL",
      interviewRequired: true,
      trainingRequired: true,
      documentVerificationRequired: true,
      stages: ["SUBMITTED", "PENDING_REVIEW", "INTERVIEW_SCHEDULED", "TRAINING", "VERIFICATION", "APPROVED"],
    },
    levelThresholds: {
      BRONZE: { minDeals: 0, minRating: 0 },
      SILVER: { minDeals: 5, minRating: 3.5 },
      GOLD: { minDeals: 15, minRating: 4 },
      PLATINUM: { minDeals: 30, minRating: 4.3 },
      ELITE: { minDeals: 50, minRating: 4.7 },
    },
    levelBenefits: {
      BRONZE: ["Verified badge", "Public profile"],
      SILVER: ["Priority leads", "Featured profile"],
      GOLD: ["Premium badge", "Homepage exposure"],
      PLATINUM: ["Top placement", "Marketing support"],
      ELITE: ["Exclusive leads", "Elite homepage feature"],
    },
    applicationFormFields: {
      nationalId: true,
      passport: true,
      policeClearance: true,
      estateAgencyLicence: false,
      references: true,
      banking: true,
    },
    notificationTemplates: {
      application_submitted: "Your HomeLink agent application has been received.",
      application_approved: "Congratulations! Your HomeLink agent application has been approved.",
      application_declined: "Your HomeLink agent application was not approved at this time.",
      interview_scheduled: "Your HomeLink agent interview has been scheduled.",
      training_assigned: "New training modules have been assigned to your agent onboarding.",
      new_lead: "You have received a new lead on HomeLink.",
      commission_paid: "Your commission payment has been processed.",
      commission_created: "A new commission has been created and is awaiting approval.",
      commission_approved: "Your commission has been approved.",
      commission_changed: "A commission percentage or rule affecting you has changed.",
      lead_ownership_changed: "A lead ownership change has been recorded by HomeLink administration.",
      transaction_closed: "A transaction has closed and the commission has been calculated.",
      review_received: "You received a new customer rating.",
    },
    commissionAuditLog: [],
    futureAgentLevels: [
      { code: "JUNIOR_AGENT", label: "Junior Agent", description: "Future-ready commission tier.", enabled: false },
      { code: "SENIOR_AGENT", label: "Senior Agent", description: "Future-ready commission tier.", enabled: false },
      { code: "PRINCIPAL_AGENT", label: "Principal Agent", description: "Future-ready commission tier.", enabled: false },
      { code: "REGIONAL_MANAGER", label: "Regional Manager", description: "Future-ready commission tier.", enabled: false },
      { code: "FRANCHISE_AGENT", label: "Franchise Agent", description: "Future-ready commission tier.", enabled: false },
    ],
    referralBonusPercent: 3,
    updatedAt: new Date().toISOString(),
  };
}

export function emptyApplicationPersonal() {
  return {
    fullName: "",
    dateOfBirth: "",
    gender: "",
    nationalId: "",
    passport: "",
    phone: "",
    whatsapp: "",
    email: "",
    residentialAddress: "",
  };
}

export function emptyApplicationProfessional() {
  return {
    yearsExperience: 0,
    currentEmployer: "",
    previousEmployer: "",
    hasDriversLicence: false,
    hasOwnVehicle: false,
    languages: [] as string[],
    province: "",
    city: "",
    areasCovered: [] as string[],
    propertyTypes: [] as string[],
    specialisations: [] as string[],
  };
}
