import type { AgentPermissions, AgentSystemSettings, AgentTrainingModule, CommissionRule } from "@/lib/agents/types";

export const DEFAULT_COMMISSION_RULES: CommissionRule[] = [
  {
    id: "rule_sale",
    type: "SALE",
    label: "Agent-sourced sale",
    leadSource: "AGENT",
    scope: "DEFAULT",
    priority: 10,
    reason: "The agent sourced the client while HomeLink provides the brand, CRM, platform, administration, and transaction support.",
    ratePercent: 5,
    homelinkSplitPercent: 40,
    agentSplitPercent: 60,
    minAmount: 0,
    maxAmount: 50000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_sale_homelink",
    type: "SALE",
    label: "HomeLink-sourced sale",
    leadSource: "HOMELINK",
    scope: "DEFAULT",
    priority: 10,
    reason: "HomeLink generated the lead through marketing, technology, brand building, support, and customer acquisition.",
    ratePercent: 5,
    homelinkSplitPercent: 60,
    agentSplitPercent: 40,
    minAmount: 0,
    maxAmount: 50000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_rental",
    type: "RENTAL",
    label: "Agent-sourced rental",
    leadSource: "AGENT",
    scope: "DEFAULT",
    priority: 10,
    reason: "The agent sourced the landlord, tenant, or room owner while HomeLink provides the operating platform and transaction support.",
    ratePercent: 10,
    homelinkSplitPercent: 40,
    agentSplitPercent: 60,
    minAmount: 0,
    maxAmount: 10000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_rental_homelink",
    type: "RENTAL",
    label: "HomeLink-sourced rental",
    leadSource: "HOMELINK",
    scope: "DEFAULT",
    priority: 10,
    reason: "HomeLink generated the enquiry and assigned an agent to inspect, verify, communicate, negotiate, and close.",
    ratePercent: 10,
    homelinkSplitPercent: 60,
    agentSplitPercent: 40,
    minAmount: 0,
    maxAmount: 10000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_management",
    type: "MANAGEMENT",
    label: "Agent-sourced management",
    leadSource: "AGENT",
    scope: "DEFAULT",
    priority: 10,
    reason: "The agent sourced the property management client; HomeLink provides the systems, brand, administration, and support.",
    ratePercent: 8,
    homelinkSplitPercent: 40,
    agentSplitPercent: 60,
    minAmount: 0,
    maxAmount: 8000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_management_homelink",
    type: "MANAGEMENT",
    label: "HomeLink-sourced management",
    leadSource: "HOMELINK",
    scope: "DEFAULT",
    priority: 10,
    reason: "HomeLink generated the management opportunity and supports the agent through operations, systems, and administration.",
    ratePercent: 8,
    homelinkSplitPercent: 60,
    agentSplitPercent: 40,
    minAmount: 0,
    maxAmount: 8000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_referral",
    type: "REFERRAL",
    label: "Referral Commission",
    leadSource: "ANY",
    scope: "DEFAULT",
    priority: 5,
    reason: "Referral commissions are shared according to the active referral rule configured by HomeLink.",
    ratePercent: 3,
    homelinkSplitPercent: 50,
    agentSplitPercent: 50,
    minAmount: 0,
    maxAmount: 5000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
  {
    id: "rule_bonus",
    type: "BONUS",
    label: "Performance Bonus",
    leadSource: "ANY",
    scope: "DEFAULT",
    priority: 5,
    reason: "Performance bonuses are set by the active HomeLink bonus rule.",
    ratePercent: 2,
    homelinkSplitPercent: 0,
    agentSplitPercent: 100,
    minAmount: 0,
    maxAmount: 3000,
    vatPercent: 0,
    bonusPercent: 2,
    active: true,
  },
  {
    id: "rule_recurring",
    type: "RECURRING",
    label: "Recurring Management",
    leadSource: "ANY",
    scope: "DEFAULT",
    priority: 5,
    reason: "Recurring management commission follows the active recurring rule configured by HomeLink.",
    ratePercent: 5,
    homelinkSplitPercent: 45,
    agentSplitPercent: 55,
    minAmount: 0,
    maxAmount: 5000,
    vatPercent: 15,
    bonusPercent: 0,
    active: true,
  },
];

export const DEFAULT_AGENT_PERMISSIONS: AgentPermissions = {
  canListProperties: true,
  canSell: true,
  canRent: true,
  canManageCommercial: true,
  canManageLand: true,
  canViewReports: true,
  canApproveOffers: false,
  canManageClients: true,
  canUploadDocuments: true,
};

export function defaultAgentTrainingModules(): AgentTrainingModule[] {
  return [
    {
      id: "train_intro",
      title: "HomeLink Agent Onboarding",
      description: "How HomeLink works, what agents are responsible for, and how trust is protected on the marketplace.",
      type: "VIDEO",
      track: "BEGINNER",
      level: "BEGINNER",
      contentUrl: "/resources/agents/homelink-agent-starter-guide.md",
      durationMinutes: 35,
      required: true,
      order: 1,
      certificateTitle: "HomeLink Agent Onboarding",
      certificateUrl: "/resources/agents/certificates/beginner-agent-certificate.md",
      manualSections: [
        { id: "manual_intro", title: "Manual placeholder", body: "Replace this with the onboarding chapter from the training manual when it is provided." },
      ],
      lessons: [
        {
          id: "intro_marketplace",
          title: "Marketplace role",
          summary: "Understand how agents support renters, buyers, landlords, owners, and property managers.",
          durationMinutes: 8,
          keyPoints: ["Protect user trust", "Keep records in HomeLink", "Do not bypass platform safety workflows"],
        },
        {
          id: "intro_conduct",
          title: "Professional conduct",
          summary: "Communication, punctuality, viewing etiquette, and client confidentiality standards.",
          durationMinutes: 12,
          keyPoints: ["Respond promptly", "Use respectful language", "Keep personal data private"],
        },
        {
          id: "intro_tools",
          title: "Agent dashboard basics",
          summary: "Use leads, listings, commissions, training, and reviews from the dashboard.",
          durationMinutes: 15,
          keyPoints: ["Update lead statuses", "Log all viewings", "Track commissions and ratings"],
        },
      ],
      resources: [
        {
          id: "agent_starter_guide",
          title: "Agent starter guide",
          description: "A quick operating guide for new HomeLink agents.",
          url: "/resources/agents/homelink-agent-starter-guide.md",
          type: "PDF",
        },
      ],
    },
    {
      id: "train_listings",
      title: "Listing Quality, Verification and Media",
      description: "How to inspect a property, collect accurate details, upload useful media, and avoid misleading listings.",
      type: "DOCUMENT",
      track: "BEGINNER",
      level: "BEGINNER",
      contentUrl: "/resources/agents/listing-quality-checklist.md",
      durationMinutes: 45,
      required: true,
      order: 2,
      certificateTitle: "Listing Quality Specialist",
      certificateUrl: "/resources/agents/certificates/beginner-agent-certificate.md",
      manualSections: [
        { id: "manual_listing", title: "Manual placeholder", body: "Replace this with the listing standards chapter from the training manual when it is provided." },
      ],
      lessons: [
        {
          id: "listing_verify",
          title: "Verify before publishing",
          summary: "Check ownership or authority, price, availability, viewing access, and safety basics.",
          durationMinutes: 15,
          keyPoints: ["Confirm landlord/owner authority", "Confirm availability date", "Record water, power, parking, and security notes"],
        },
        {
          id: "listing_media",
          title: "Photo and video standards",
          summary: "Capture clear, current, well-lit media that shows the actual property condition.",
          durationMinutes: 15,
          keyPoints: ["Use recent photos", "Show every key room", "Avoid misleading crops or filters"],
        },
        {
          id: "listing_copy",
          title: "Writing trusted listings",
          summary: "Write titles, descriptions, amenities, and rules that help users make informed decisions.",
          durationMinutes: 15,
          keyPoints: ["Mention location accurately", "Declare fees clearly", "Keep descriptions factual"],
        },
      ],
      resources: [
        {
          id: "listing_quality_checklist",
          title: "Listing quality checklist",
          description: "Inspection and publishing checklist for rentals, sales, rooms, and holiday homes.",
          url: "/resources/agents/listing-quality-checklist.md",
          type: "CHECKLIST",
        },
        {
          id: "viewing_inspection_sheet",
          title: "Viewing inspection sheet",
          description: "Reusable worksheet for property viewings and inspections.",
          url: "/resources/agents/viewing-inspection-sheet.md",
          type: "TEMPLATE",
        },
      ],
    },
    {
      id: "train_leads",
      title: "Lead Handling and Tenant Protection",
      description: "How to respond to leads, schedule safe viewings, prevent fraud, and record deal outcomes.",
      type: "QUIZ",
      track: "VERIFIED_AGENT",
      level: "INTERMEDIATE",
      contentUrl: "/resources/agents/lead-handling-playbook.md",
      durationMinutes: 40,
      required: true,
      order: 3,
      certificateTitle: "Lead Handling Certified",
      certificateUrl: "/resources/agents/certificates/verified-agent-certificate.md",
      lessons: [
        {
          id: "lead_sla",
          title: "Lead response standards",
          summary: "Prioritise fresh leads, confirm user needs, and update the CRM status quickly.",
          durationMinutes: 10,
          keyPoints: ["Respond fast", "Keep conversations in HomeLink", "Update status after every action"],
        },
        {
          id: "lead_viewings",
          title: "Safe viewing workflow",
          summary: "Use confirmed times, verified contacts, and clear viewing instructions.",
          durationMinutes: 12,
          keyPoints: ["Confirm identity", "Never pressure deposits before due diligence", "Record viewing results"],
        },
        {
          id: "lead_fraud",
          title: "Fraud and scam prevention",
          summary: "Spot red flags and escalate suspicious listings, payments, or user behaviour.",
          durationMinutes: 18,
          keyPoints: ["Check payment destination", "Escalate suspicious urgency", "Never hide platform records"],
        },
      ],
      quiz: {
        passMark: 80,
        questions: [
          {
            id: "lead_q1",
            prompt: "A renter asks to pay a deposit before viewing. What should the agent do first?",
            options: ["Encourage immediate payment", "Confirm property details and safe due diligence first", "Move the chat off-platform", "Ignore the lead"],
          },
          {
            id: "lead_q2",
            prompt: "Where should important lead updates be recorded?",
            options: ["Only in a personal notebook", "Only on WhatsApp", "Inside the HomeLink lead workflow", "After the deal closes only"],
          },
          {
            id: "lead_q3",
            prompt: "What is a clear fraud warning sign?",
            options: ["A user asks for viewing times", "A landlord provides documents", "Pressure to send money urgently to an unverified account", "A tenant asks about Wi-Fi"],
          },
          {
            id: "lead_q4",
            prompt: "After a viewing, what should the agent update?",
            options: ["Nothing until payment", "Lead status, notes, next step, and outcome", "Only the commission page", "Only the public listing title"],
          },
          {
            id: "lead_q5",
            prompt: "What should an agent do if a listing looks duplicated or misleading?",
            options: ["Publish it anyway", "Escalate or flag it for review", "Delete user messages", "Ask for cash to fix it"],
          },
        ],
      },
      resources: [
        {
          id: "lead_handling_playbook",
          title: "Lead handling playbook",
          description: "Scripts, statuses, and safe viewing workflow for agent leads.",
          url: "/resources/agents/lead-handling-playbook.md",
          type: "PDF",
        },
      ],
    },
    {
      id: "train_compliance",
      title: "Compliance, Ethics and Documentation",
      description: "Client privacy, fair treatment, record keeping, verification, and professional boundaries.",
      type: "ASSIGNMENT",
      track: "VERIFIED_AGENT",
      level: "INTERMEDIATE",
      contentUrl: "/resources/agents/compliance-ethics-handbook.md",
      durationMinutes: 50,
      required: true,
      order: 4,
      certificateTitle: "Compliance and Ethics",
      certificateUrl: "/resources/agents/certificates/verified-agent-certificate.md",
      expiresAfterDays: 365,
      lessons: [
        {
          id: "compliance_privacy",
          title: "Privacy and personal data",
          summary: "Handle IDs, phone numbers, documents, and addresses only for legitimate HomeLink workflows.",
          durationMinutes: 15,
          keyPoints: ["Do not leak user data", "Use approved upload flows", "Share only what is needed"],
        },
        {
          id: "compliance_fairness",
          title: "Fair treatment",
          summary: "Avoid discriminatory screening and communicate requirements transparently.",
          durationMinutes: 15,
          keyPoints: ["Apply rules consistently", "Avoid discriminatory language", "Document objective criteria"],
        },
        {
          id: "compliance_records",
          title: "Documentation and escalation",
          summary: "Keep verification, agreements, proof of payment, and disputes traceable.",
          durationMinutes: 20,
          keyPoints: ["Record decisions", "Escalate safety issues", "Keep agreements and receipts attached"],
        },
      ],
      resources: [
        {
          id: "compliance_handbook",
          title: "Compliance and ethics handbook",
          description: "Practical operating rules for privacy, documentation, and marketplace safety.",
          url: "/resources/agents/compliance-ethics-handbook.md",
          type: "PDF",
        },
      ],
    },
    {
      id: "train_pm",
      title: "Property Management Operations",
      description: "How agents coordinate maintenance, inspections, owner requests, quotes, invoices, and service records.",
      type: "DOCUMENT",
      track: "PROPERTY_MANAGER",
      level: "ADVANCED",
      contentUrl: "/resources/agents/property-management-operations.md",
      durationMinutes: 35,
      required: false,
      order: 5,
      certificateTitle: "Property Manager Track",
      certificateUrl: "/resources/agents/certificates/property-manager-certificate.md",
      lessons: [
        {
          id: "pm_intake",
          title: "Request intake",
          summary: "Capture owner, property, priority, photos, and access notes before assigning work.",
          durationMinutes: 12,
          keyPoints: ["Clarify scope", "Collect evidence", "Set expectations"],
        },
        {
          id: "pm_delivery",
          title: "Quotes, invoices and completion",
          summary: "Coordinate quotations, owner approvals, invoices, and completion records.",
          durationMinutes: 23,
          keyPoints: ["Use written approvals", "Attach documents", "Close work with proof"],
        },
      ],
      resources: [
        {
          id: "pm_operations",
          title: "Property management operations guide",
          description: "Process guide for managed property requests.",
          url: "/resources/agents/property-management-operations.md",
          type: "PDF",
        },
      ],
    },
    {
      id: "train_growth",
      title: "Commissions, Reviews and Agent Growth",
      description: "Understand commission splits, ratings, public profiles, client follow-up, and growth tiers.",
      type: "DOCUMENT",
      track: "SENIOR_AGENT",
      level: "ADVANCED",
      contentUrl: "/resources/agents/commission-and-growth-guide.md",
      durationMinutes: 30,
      required: false,
      order: 6,
      certificateTitle: "Senior Agent Growth Track",
      certificateUrl: "/resources/agents/certificates/senior-agent-certificate.md",
      lessons: [
        {
          id: "growth_commissions",
          title: "Commission rules",
          summary: "Know the difference between HomeLink-sourced, agent-sourced, referral, and recurring commissions.",
          durationMinutes: 15,
          keyPoints: ["Check rule snapshots", "Close leads properly", "Keep payment records clean"],
        },
        {
          id: "growth_reviews",
          title: "Reviews and trust",
          summary: "Use excellent service and complete records to improve your public reputation.",
          durationMinutes: 15,
          keyPoints: ["Ask for honest reviews", "Resolve issues quickly", "Keep your profile current"],
        },
      ],
      resources: [
        {
          id: "commission_growth",
          title: "Commission and growth guide",
          description: "Guide to earning, reviews, profile quality, and progression.",
          url: "/resources/agents/commission-and-growth-guide.md",
          type: "PDF",
        },
      ],
    },
  ];
}

export function createDefaultAgentSettings(): AgentSystemSettings {
  return {
    commissionRules: DEFAULT_COMMISSION_RULES.map((r) => ({ ...r })),
    leadAssignmentStrategy: "TERRITORY",
    approvalWorkflow: {
      mode: "MANUAL",
      interviewRequired: true,
      trainingRequired: true,
      documentVerificationRequired: true,
      stages: ["SUBMITTED", "PENDING_REVIEW", "INTERVIEW_SCHEDULED", "TRAINING", "VERIFICATION", "APPROVED"],
    },
    levelThresholds: {
      BRONZE: { minDeals: 0, minRating: 0 },
      SILVER: { minDeals: 5, minRating: 3.5 },
      GOLD: { minDeals: 15, minRating: 4 },
      PLATINUM: { minDeals: 30, minRating: 4.3 },
      ELITE: { minDeals: 50, minRating: 4.7 },
    },
    levelBenefits: {
      BRONZE: ["Verified badge", "Public profile"],
      SILVER: ["Priority leads", "Featured profile"],
      GOLD: ["Premium badge", "Homepage exposure"],
      PLATINUM: ["Top placement", "Marketing support"],
      ELITE: ["Exclusive leads", "Elite homepage feature"],
    },
    applicationFormFields: {
      nationalId: true,
      passport: true,
      policeClearance: true,
      estateAgencyLicence: false,
      references: true,
      banking: true,
    },
    notificationTemplates: {
      application_submitted: "Your HomeLink agent application has been received.",
      application_approved: "Congratulations! Your HomeLink agent application has been approved.",
      application_declined: "Your HomeLink agent application was not approved at this time.",
      interview_scheduled: "Your HomeLink agent interview has been scheduled.",
      training_assigned: "New training modules have been assigned to your agent onboarding.",
      new_lead: "You have received a new lead on HomeLink.",
      commission_paid: "Your commission payment has been processed.",
      commission_created: "A new commission has been created and is awaiting approval.",
      commission_approved: "Your commission has been approved.",
      commission_changed: "A commission percentage or rule affecting you has changed.",
      lead_ownership_changed: "A lead ownership change has been recorded by HomeLink administration.",
      transaction_closed: "A transaction has closed and the commission has been calculated.",
      review_received: "You received a new customer rating.",
    },
    commissionAuditLog: [],
    futureAgentLevels: [
      { code: "JUNIOR_AGENT", label: "Junior Agent", description: "Future-ready commission tier.", enabled: false },
      { code: "SENIOR_AGENT", label: "Senior Agent", description: "Future-ready commission tier.", enabled: false },
      { code: "PRINCIPAL_AGENT", label: "Principal Agent", description: "Future-ready commission tier.", enabled: false },
      { code: "REGIONAL_MANAGER", label: "Regional Manager", description: "Future-ready commission tier.", enabled: false },
      { code: "FRANCHISE_AGENT", label: "Franchise Agent", description: "Future-ready commission tier.", enabled: false },
    ],
    referralBonusPercent: 3,
    updatedAt: new Date().toISOString(),
  };
}

export function emptyApplicationPersonal() {
  return {
    fullName: "",
    dateOfBirth: "",
    gender: "",
    nationalId: "",
    passport: "",
    phone: "",
    whatsapp: "",
    email: "",
    residentialAddress: "",
  };
}

export function emptyApplicationProfessional() {
  return {
    yearsExperience: 0,
    currentEmployer: "",
    previousEmployer: "",
    hasDriversLicence: false,
    hasOwnVehicle: false,
    languages: [] as string[],
    province: "",
    city: "",
    areasCovered: [] as string[],
    propertyTypes: [] as string[],
    specialisations: [] as string[],
  };
}
