ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'DELETED';

ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "featuredUntil" TIMESTAMP(3);
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "views" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "accountStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);

ALTER TABLE "RoommateProfile" ADD COLUMN IF NOT EXISTS "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "RoommateProfile" ADD COLUMN IF NOT EXISTS "payload" JSONB;

ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "plan" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "method" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "manual" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "proofUrl" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "proofStatus" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
