import { roommatePortraits, seekerCoverPhotos, testimonialPhotos } from "@/lib/roommates/media";

export const roommateTrustBadges = [
  "Verified profiles",
  "Safe & trusted",
  "Easy matching",
  "Secure chat",
] as const;

export const roommateAmenityFilters = [
  "Furnished",
  "Wi-Fi",
  "Parking",
  "Borehole",
  "Solar backup",
  "Pet friendly",
] as const;

export const roommateProblemPoints = [
  "Scrolling WhatsApp groups for hours with no verified listings",
  "Paying deposits before meeting landlords or seeing the room",
  "Moving in with strangers who don't match your lifestyle",
] as const;

export const roommateSolutionPoints = [
  "Browse verified rooms with photos, prices, and move-in dates",
  "Match with compatible roommates by budget, habits, and location",
  "Chat securely, visit safely, and move in with confidence",
] as const;

export const audiencePaths = [
  {
    id: "need-room",
    title: "I need a room",
    body: "Student, professional, or relocating - find verified rooms in your budget.",
    cta: "Find a room",
    href: "/search?type=room&intent=rent",
    icon: "search" as const,
  },
  {
    id: "have-room",
    title: "I have a room to share",
    body: "Fill your empty room with someone trustworthy. List free in minutes.",
    cta: "Post my room",
    href: "/dashboard/landlord/new",
    icon: "home" as const,
  },
  {
    id: "need-roommate",
    title: "I need a roommate",
    body: "Already renting? Split costs with a compatible, verified housemate.",
    cta: "Find a roommate",
    href: "/roommates/profile",
    icon: "users" as const,
  },
] as const;

export const roommateSteps = [
  {
    step: 1,
    title: "Choose your path",
    body: "Tell HomeLink if you need a room, have a room, or want a roommate.",
    icon: "profile" as const,
  },
  {
    step: 2,
    title: "Add the essentials",
    body: "Set the location, budget or rent, move-in date, lifestyle, and must-haves.",
    icon: "browse" as const,
  },
  {
    step: 3,
    title: "Upload real photos",
    body: "Hosts add clear room, kitchen, bathroom, entrance, and shared-space photos.",
    icon: "chat" as const,
  },
  {
    step: 4,
    title: "Review matches",
    body: "Compare verified rooms and compatible people by price, area, habits, and safety signals.",
    icon: "visit" as const,
  },
  {
    step: 5,
    title: "Chat, view, move",
    body: "Message securely, schedule a viewing, confirm details, and move in with confidence.",
    icon: "move" as const,
  },
] as const;

export const trustFeatures = [
  { title: "Identity verification", body: "Government ID and phone checks on every profile." },
  { title: "Verified listings", body: "Landlords and rooms reviewed before going live." },
  { title: "Secure messaging", body: "End-to-end chat - no sharing personal numbers early." },
  { title: "Report & block", body: "Flag suspicious users. Our team responds within hours." },
  { title: "Reviews & ratings", body: "Real feedback from completed stays and matches." },
  { title: "Safety tips", body: "Community guidelines and scam detection built in." },
] as const;

export const communityActivity = [
  { label: "Rooms filled today", value: "47", trend: "+12%" },
  { label: "New listings", value: "23", trend: "Live" },
  { label: "Matches this week", value: "186", trend: "+8%" },
  { label: "Active seekers", value: "312", trend: "Now" },
] as const;

export const trendingLocations = [
  { name: "Avondale, Harare", href: "/search?city=Harare&suburb=Avondale&type=room" },
  { name: "Senga, Gweru", href: "/search?city=Gweru&suburb=Senga&type=room" },
  { name: "Hillside, Bulawayo", href: "/search?city=Bulawayo&suburb=Hillside&type=room" },
  { name: "Newtown, Kwekwe", href: "/search?city=Kwekwe&type=room" },
] as const;

export const recommendedRoommates = [
  {
    id: "user_seeker_rudo",
    name: "Rudo M.",
    city: "Harare",
    suburb: "Avondale",
    budgetMin: 220,
    budgetMax: 320,
    gender: "Female",
    age: 27,
    occupation: "Professional",
    lifestyle: "quiet",
    availableFrom: "1 Aug 2026",
    verified: true,
    lookingFor: "room" as const,
    tags: ["Non-smoker", "Quiet", "Wi-Fi"],
    smoking: false,
    pets: false,
    languages: ["English", "Shona"],
    compatibility: 94,
    interests: ["Early mornings", "Wi-Fi", "Quiet household"],
    avatarUrl: roommatePortraits.rudo,
    coverPhoto: seekerCoverPhotos.professional,
  },
  {
    id: "user_seeker_taku",
    name: "Taku N.",
    city: "Gweru",
    suburb: "Senga",
    budgetMin: 120,
    budgetMax: 180,
    gender: "Male",
    age: 22,
    occupation: "MSU student",
    lifestyle: "student",
    availableFrom: "Available now",
    verified: true,
    lookingFor: "room" as const,
    tags: ["Student", "Transport", "Shared kitchen"],
    smoking: false,
    pets: false,
    languages: ["English", "Shona"],
    compatibility: 88,
    interests: ["Near campus", "Shared kitchen", "Transport"],
    avatarUrl: roommatePortraits.taku,
    coverPhoto: seekerCoverPhotos.student,
  },
  {
    id: "user_seeker_noma",
    name: "Noma S.",
    city: "Bulawayo",
    suburb: "Hillside",
    budgetMin: 180,
    budgetMax: 260,
    gender: "Female",
    age: 29,
    occupation: "Hybrid worker",
    lifestyle: "professional",
    availableFrom: "15 Jul 2026",
    verified: true,
    lookingFor: "room" as const,
    tags: ["Pets OK", "Parking", "Furnished"],
    smoking: false,
    pets: true,
    languages: ["English", "Ndebele"],
    compatibility: 91,
    interests: ["Pet-friendly", "Parking", "Hybrid work"],
    avatarUrl: roommatePortraits.noma,
    coverPhoto: seekerCoverPhotos.hybrid,
  },
  {
    id: "user_seeker_chipo",
    name: "Chipo D.",
    city: "Harare",
    suburb: "Belvedere",
    budgetMin: 150,
    budgetMax: 220,
    gender: "Female",
    age: 24,
    occupation: "Nurse",
    lifestyle: "professional",
    availableFrom: "Available now",
    verified: true,
    lookingFor: "room" as const,
    tags: ["Furnished", "Parking", "Quiet"],
    smoking: false,
    pets: false,
    languages: ["English", "Shona"],
    compatibility: 86,
    interests: ["Night shift friendly", "Parking", "Furnished"],
    avatarUrl: roommatePortraits.chipo,
    coverPhoto: seekerCoverPhotos.nurse,
  },
  {
    id: "user_seeker_farai",
    name: "Farai T.",
    city: "Mutare",
    suburb: "Chikanga",
    budgetMin: 90,
    budgetMax: 140,
    gender: "Male",
    age: 21,
    occupation: "Intern",
    lifestyle: "student",
    availableFrom: "1 Sep 2026",
    verified: false,
    lookingFor: "room" as const,
    tags: ["Budget", "Wi-Fi", "Shared kitchen"],
    smoking: false,
    pets: false,
    languages: ["English", "Shona"],
    compatibility: 82,
    interests: ["Budget-friendly", "Wi-Fi", "Shared kitchen"],
    avatarUrl: roommatePortraits.farai,
    coverPhoto: seekerCoverPhotos.intern,
  },
  {
    id: "user_seeker_grace",
    name: "Grace M.",
    city: "Harare",
    suburb: "Borrowdale",
    budgetMin: 280,
    budgetMax: 400,
    gender: "Female",
    age: 31,
    occupation: "Accountant",
    lifestyle: "professional",
    availableFrom: "20 Aug 2026",
    verified: true,
    lookingFor: "room" as const,
    tags: ["House share", "Parking", "Security"],
    smoking: false,
    pets: false,
    languages: ["English", "Shona"],
    compatibility: 90,
    interests: ["House share", "Secure estate", "Parking"],
    avatarUrl: roommatePortraits.grace,
    coverPhoto: seekerCoverPhotos.accountant,
  },
] as const;

export const roommateStats = [
  { label: "Successful matches", value: "92%" },
  { label: "Happy members", value: "18K+" },
  { label: "Support", value: "24/7" },
] as const;

export const successStories = [
  {
    name: "Tendai K.",
    role: "MSU student",
    city: "Gweru",
    quote: "I found a room near campus within a week. The landlord was verified and the whole process felt safe.",
    outcome: "Moved in under US$150/month",
    avatarUrl: roommatePortraits.tendai,
    coverPhoto: testimonialPhotos[0],
  },
  {
    name: "Rudo M.",
    role: "Young professional",
    city: "Harare",
    quote: "HomeLink made it easy to compare rooms in Avondale. I messaged the landlord securely before viewing.",
    outcome: "Found a quiet room in 5 days",
    avatarUrl: roommatePortraits.rudo,
    coverPhoto: testimonialPhotos[1],
  },
  {
    name: "Blessing N.",
    role: "Hybrid worker",
    city: "Bulawayo",
    quote: "The trust badges and verified profiles gave me confidence. My roommate and I matched on lifestyle too.",
    outcome: "92% compatibility match",
    avatarUrl: roommatePortraits.blessing,
    coverPhoto: testimonialPhotos[2],
  },
] as const;
